### ISSUE TITLE
Unable to load extension (QGIS 3.2)

### ISSUE THREAD

**Issue by Marwe** [gacarrillor/loadthemall#11]
Thanks for this wonderful plugin.

I just switched to 3.2 and cannot load the plugin any more. Any hints about this? 

locale seems to be the issue here, I guess it is a name clash (no - I tried changing the variable name),
on the Python console the result is `NULL` for `QSettings().value("locale/userLocale", type=str)`, but I guess that may be out of context anyway.

~~~
Konnte Erweiterung 'loadthemall' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.2/apps/qgis/./python\qgis\utils.py", line 337, in startPlugin
  File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\loadthemall\__init__.py", line 25, in classFactory
    plugins[packageName] = package.classFactory(iface)
    return LoadThemAll(iface)
  File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\loadthemall\LoadThemAll.py", line 46, in __init__
    self.installTranslator()
  File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\loadthemall\LoadThemAll.py", line 80, in installTranslator
    myLocale = str( locale[0:2] )
TypeError: 'QVariant' object is not subscriptable


Python-Version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS-Version: 3.2.3-Bonn Bonn, 9b176802e5 
~~~

BTW, I was running on Windows (OSgeo4W installation)

**Comment by Marwe** [comment]
The "locale/userLocale" is NULL here, but it appears in `QSettings().allKeys()`.

**Comment by Marwe** [comment]
Setting a locale explicitly via Settings-Options-General-"override system locale" solves it for now. But code nees a check here.

**Comment by Marwe** [comment]
Check might be like this (taking en as default):

~~~
    locale = QSettings().value("locale/userLocale", type=str)
    myLocale = "en"
    if isinstance(locale, basestring):
        myLocale = str( locale[0:2] )
~~~

Sorry, I don't have a proper dev environment here, so not as proper patch/PR.
And cannot test properly, since unsetting "override locale" in options changes to system locale (not back to NULL). Seems to be a problem after fresh install (+ migrate profile from 2.18)

**Comment by gacarrillor** [comment]
Thanks a lot for the report!
I'll fix this in a while.

Regards.

**Comment by omichalek** [comment]
I am on 3.14 using flatpak and I cannot start your plugin either.
I tried setting few locales as well as language from the settings but it did not help.

**Comment by gacarrillor** [comment]
Can you share more details? Do you get any error message?

**Comment by omichalek** [comment]
There are no error messages, it just does not do anything at all
- Running with `$ flatpak --verbose run org.qgis.qgis` there are not messages in the terminal either after selecting the plugin from menu.
- I also installed QGIS 3.14 version on Windows and your plugin does not start there either.
(I have one other plugin - DirectionalSlope - and it does launch.)

**Comment by gacarrillor** [comment]
Strange, just tested it on a Windows (fresh install) without problems.

**Comment by gacarrillor** [comment]
@omichalek Could you give the following .zip file a try? (I've adjusted `QLocale` related code on it.)

Just install it from `Plugins` --> `Manage and Install Plugins...` --> `Install from ZIP`.

[loadthemall.zip](https://github.com/gacarrillor/loadthemall/files/5087689/loadthemall.zip)
