### ISSUE TITLE
Proposal : apply qml on a directory level

### ISSUE THREAD

**Issue by jhemmi** [gacarrillor/loadthemall#12]
Even if Q3 help to apply styles, i beleive it could be helpful to apply a style on a directory level.
For instance the QML is applyable when his name is the same of the directory

**Comment by gacarrillor** [comment]
Thanks for your interest in the plugin!
Load Them All does not really deal with any layer style. 

Do you think the plugin could apply styles at layer-load time?

Germán

**Comment by jhemmi** [comment]
Yes, `loadNamedStyle` could apply a style during loading, i've already used this with qml.
 
The point is how to match the layer and his style ? I propose
- to manage one style (qml) with the directory name (group) to apply to all layers
- to manage one specific style for a layer having the layer name ... i'am not sure this can be so easy to explain to users... 

Jean

**Comment by jhemmi** [comment]
I do think both are useful.
If you need any help for test for instance.

**Comment by gacarrillor** [comment]
For the first option, some tests are required before considering it. For instance, what if the group style doesn't have all layers that are inside the corresponding folder? Will those layers be shown in the QGIS layer panel?

**Comment by jhemmi** [comment]
Style doesn't avoid to load layer. If no style are found, it have to work as now.
Perhaps options 1 & 2 are to be re-ordered:

When a style has the layer name, this style applies during loading.
Else when a style is present in the folder (with the name of the folder), all layers inside this folder apply this style.

**Comment by gacarrillor** [comment]
Good, thanks for the proposal.
At this point it will not have a high priority due to shortage of time.
Are you fine with it? If not, do you have programming skills or could consider funding the feature so that it gets into the plugin soon?

**Comment by jhemmi** [comment]
Fine if it's clear for you !
I have few time next week. I can python it, for the qml case. Are your OK to test and control merge in github ? The best way is to create a new branch ?

I should translate LoadThemAll in French in the session. You haven't use the I18 method ?  
My email is jean at jhemmi dot eu

**Comment by gacarrillor** [comment]
Great, this is the procedure:
You  fork the reposiitory, create a new branch in your copied repo, do the changes, commit and push to your branch, and then create a Pull Request to my master branch.

I'd like to let the user choose whether she wants to attempt to load styles if found. By default this option would be False. The option should appear in the `Configuration` tab.

Regarding the translation, we already translated the plugin into Spanish, there is a `loadthemall_es.ts` file in the plugin. We would need to create a `loadthemall_fr.ts` file with the translations.

(I'll contact you by e-mail soon)

**Comment by jhemmi** [comment]
Fork on progress

**Comment by gacarrillor** [comment]
Implemented in PR #16!
