### ISSUE TITLE
Enhancement Request: Define/Use Default CRS

### ISSUE THREAD

**Issue by Saijin-Naib** [gacarrillor/loadthemall#14]
One of my main uses of LoadThemAll is to integrate agricultural data from Trimble AgGPS farming equipment.

LoadThemAll does a brilliant job of recursion, finding all the shapefile data and grouping/naming them in a very legible manner.

However, many different types of agricultural data do NOT specify a CRS using metadata or a .prj file, and WGS84 (EPSG:4326) is assumed & used internally without the explicit definition.

My request for improvement would be if we could define (prior to import, with hopefully a sticky settings toggle like all other LoadThemAll options) a default CRS to be used by LoadThemAll to be passed to QGIS when a layer is indexed/loaded that does NOT have a .prj file accompanying it.

For instance, I'm going to have to manually define the projection for 1,059 layers before I can successfully load and inspect this data.

Thanks!

**Comment by gacarrillor** [comment]
@Saijin-Naib 
Does this QGIS 'Default CRS for layers' option solves your issue? Of course, choosing 'Use default layer CRS' as well.
![image](https://user-images.githubusercontent.com/652785/129829275-cef4ebad-389c-4b04-b4c4-0031769f4b96.png)

**Comment by Saijin-Naib** [comment]
> @Saijin-Naib
> Does this QGIS 'Default CRS for layers' option solves your issue? Of course, choosing 'Use default layer CRS' as well.


I no longer have access to the datasets/devices that I was using for this use-case, so I can no longer confirm (changed jobs/industries).

Maybe close for now and I can re-open if that changes?

**Comment by gacarrillor** [comment]
Ok, we can close it because I tested the option I mentioned in the last comment and it seems to solve your issue.

If you or anybody else find something that should be in Load Them All regarding CRSs, please reopen or, if it's not related to this issue, create a new one.
