### ISSUE TITLE
Load zipped shp files 

### ISSUE THREAD

**Issue by kilobike** [gacarrillor/loadthemall#19]
Hey,
I absolutely love to load them all. Particularly we have a large number of shape files in a directory tree that we can easily suck in. 
What I'd love to do however, is pack the whole directory tree containing gazillions of shp files ( they pack really nice) and use Load them all to load them from zip, as if using the regular vector layer loader.

**Comment by gacarrillor** [comment]
Hi @kilobike 

you cannot say you love it if you haven't starred it! :stuck_out_tongue: 
Just joking, great that you find it useful. 

That's a very nice idea! If you would like to see it implemented soon (let's say by the end of July), please consider funding its development. Of course, if you can develop it by yourself, code contributions are welcomed.

Regards, 

Germán

**Comment by pitney123456** [comment]
I want to second this request since with my 10,000(s) of raster files I need to store them zipped.
My workaround is to select all the .zip files in a continent, select "Extract Here" and then load the unzipped files with "Load Them All"
hanks for a very useful plugin!
pitney

**Comment by gacarrillor** [comment]
Good news @kilobike and @pitney123456 (and @agiudiceandrea :smiley: ) !

Zipped files support is now in beta status. :tada: 

If you happen to be available to do some testing, please use the following plugin beta version and let me know if everything goes as expected.

[loadthemall.zip](https://github.com/gacarrillor/loadthemall/files/12832816/loadthemall.zip)

This version will find and load your files even if they are inside a .ZIP files.
If the ZIP file has another ZIP file inside, which contains a file matching your filters, it'll be loaded as well!

**Comment by gacarrillor** [comment]
(Just merged into master to ease integration of incoming 3rd party contributions)

Tests would be still appreciated if you guys find the time.

**Comment by gacarrillor** [comment]
Gentle ping @kilobike and @pitney123456
