### ISSUE TITLE
Enhancement Request: add .ers filetype to raster loading

### ISSUE THREAD

**Issue by AuSpotter** [gacarrillor/loadthemall#21]
Hello, I really like the utility of Load Them All, but there are a number of semi-common grid files that aren't recognised by the raster option (e.g., ers).

Could it be possible to add these?

**Comment by gacarrillor** [comment]
Hi, could you point me to some data samples so that I can test when I add the new option?
Let me know if there are other extensions that should be added.

**Comment by AuSpotter** [comment]
Thanks for the quick reply! I'll have to look for some public example (the files I'm using are confidential).

More details for the format are here: https://gdal.org/drivers/raster/ers.html

**Comment by gacarrillor** [comment]
.ers format has been added. 

Don't forget you can suggest other formats as well.
