### ISSUE TITLE
Delimited text

### ISSUE THREAD

**Issue by otofoto** [gacarrillor/loadthemall#23]
How to change delimiter/separator when importing CSV files? Does it uses active regional settings?

**Comment by gacarrillor** [comment]
CSV (customization) support will be added in future releases.

------------------
Note to self: https://github.com/qgis/QGIS/blob/a8de679601be931bd356a69f4b1cbb224581339d/src/providers/delimitedtext/qgsdelimitedtextsourceselect.cpp#L107-L219

**Comment by gacarrillor** [comment]
Closing, as "customize loading of CSV files" is a duplicate of https://github.com/gacarrillor/loadthemall/issues/7
