### ISSUE TITLE
Add .jp2 image format

### ISSUE THREAD

**Issue by matt-dell** [gacarrillor/loadthemall#26]
would like this feature to help with bulk loading of Sentinel satellite data
thanks for the great plugin

**Comment by glostis** [comment]
Hi @matt-dell 

It's a fun coincidence that I stumbled the same problem as you did today!
I've opened PR #27 to add support for JPEG2000.
If it doesn't get merged and released soon enough, you can always download my branch as a zip ([link](https://github.com/glostis/loadthemall/archive/refs/heads/feature/add-jpeg2000.zip)) and install the zip directly in QGIS' plugin manager.

**Comment by gacarrillor** [comment]
Thank you @matt-dell for your suggestion.

We'll add some new extensions in v3.3.0, including .jp2.
