### ISSUE TITLE
Possibility of using an exception in alphanumerical filters & filter other fields in folder

### ISSUE THREAD

**Issue by BC14w** [gacarrillor/loadthemall#5]
Hi,
If the alphanumerical filter could use an exception instead of an and/or, it could be faster if you want all the data except files with a certain name. 
Also, I am trying to filter for files that were modified last. Would it be possible filter for other fields than 'file name', such as 'Date modified'
Thanks,
B-C

**Comment by gacarrillor** [comment]
Hi B-C, 

thanks for suggesting improvements. Inverted Alphanumeric filter is now in master branch. I would acknowledge if you can give it a try and send me some feedback. 

I'll see how feasible and convenient the "Date modified" filter is. If it's not, I'll release a new version of LoadThemAll with only Inverted Alphanumeric filter.

Regards, 
Germán

**Comment by BC14w** [comment]
Hi Germán,
Thanks for the invert filter! It works great. The box is super user friendly!
Thanks,
B-C

**Comment by gacarrillor** [comment]
Great! You can find the 'invert alphanumeric filter' functionality in [Load Them All v2.6](http://plugins.qgis.org/plugins/loadthemall/).

If you would really like to have a 'modification date' filter, please open a new issue (one issue per topic) and explain a bit more how do you envision such filter.

Thanks once more for your suggestions.

**Comment by BC14w** [comment]
Thanks Germán,
I just added the other issue. Let me know if you need more information and if you think it' possible!
Thanks

**Comment by gacarrillor** [comment]
Thanks, I think it's clearer now and I think it's doable. 
I'll check it out when I can make some time for it.

Regards, 
Germán

**Comment by BC14w** [comment]
Great to hear!
Thanks,
B-C
