### ISSUE TITLE
"Date modified" Filter

### ISSUE THREAD

**Issue by BC14w** [gacarrillor/loadthemall#6]
Hi,
I was wondering if it would be possible to add a filter based on date modified in the folder. It would be nice to load only the new data that hasn't been worked on in a project. Using operators in the filter such as <, = and > would make it super useful. e.g. loading only dates after 2016-06-12 using '>2016-06-12'.
Thanks,

**Comment by gacarrillor** [comment]
Hi @BC14w, 

Date modified filter is now in master branch. Please give it a try and let me know if it works as expected.
I'll be releasing Load Them All v2.7 probably on next Tuesday or Wednesday.

Regards, 
Germán

**Comment by BC14w** [comment]
Hi @gacarrillor ,
Thanks a lot!
I've just tried it and I seem to be getting an error:
WindowsError: [Error 123] The filename, directory name or volume label syntax is incorrect
When I use the plugin without the date modified filter, the plugin still works, but when I add this filter it does that. 
I've also noticed that when there is an error the plugin does not reset and the button to load them all stays at cancel.
Let me know if you need anymore information.
Thanks,
B-C

**Comment by gacarrillor** [comment]
Hi @BC14w,

I just tested the plugin on Windows and had no problem. Please let me know more details about your configuration, for instance: What is your base directory? What QGIS version do you use?

I'll give it a second try on Windows tomorrow at the office. 

Regards,
Germán

**Comment by BC14w** [comment]
Hi Germán,
Thanks for looking into this. and, yes the cancel button is fixed on my end too! thanks!
I've actually tried opening shapefiles with the filter, and it worked. It's only when I try loading gpx files that I seem to get a problem.
This is the full python error:
2017-07-12T08:03:44	1	Traceback (most recent call last):
			  File "C:/Users/BC14w/.qgis2/python/plugins\loadthemall-master\LoadThemAllDialog.py", line 261, in load
			    self.apply()
			  File "C:/Users/BC14w/.qgis2/python/plugins\loadthemall-master\LoadThemAllDialog.py", line 203, in apply
			    filterList )
			  File "C:/Users/BC14w/.qgis2/python/plugins\loadthemall-master\LoadFiles.py", line 211, in __init__
			    if self.getFilesToLoad():
			  File "C:/Users/BC14w/.qgis2/python/plugins\loadthemall-master\LoadFiles.py", line 90, in getFilesToLoad
			    if self.applyFilter( path ): # The layer passes the filter?
			  File "C:/Users/BC14w/.qgis2/python/plugins\loadthemall-master\LoadFiles.py", line 39, in applyFilter
			    return self.filterList.apply( layerBaseName )
			  File "C:/Users/BC14w/.qgis2/python/plugins\loadthemall-master\Filter.py", line 218, in apply
			    check = filter.apply( layerPath )
			  File "C:/Users/BC14w/.qgis2/python/plugins\loadthemall-master\Filter.py", line 150, in apply
			    dateModified = QDateTime().fromString( time.ctime( os.path.getmtime( layerPath ) ) )
			  File "C:\OSGEO4~1\apps\Python27\lib\genericpath.py", line 54, in getmtime
			    return os.stat(filename).st_mtime
			WindowsError: [Error 123] The filename, directory name or volume label syntax is incorrect: u'C:\\Users\\BC14w\\ownCloud\\Canfor - PG Timber\\Layout Blocks\\CP_UT3_KEN004\\5. Daily Garmin Dump\\KEN004_AP.gpx|layername=waypoints'

Let me know what you think.

Thanks,

**Comment by gacarrillor** [comment]
Ah, good! Thanks. That error message gave me enough hints. It should be fixed now in master. Please try one last time. If that's successful, I'll release v2.7 right away.

Regards, 

Germán

**Comment by BC14w** [comment]
Yes, works like a charm now!
Great, well played Sir!
Thank you.
B-C

**Comment by gacarrillor** [comment]
The new version is out with your suggestions!
Thanks for your involvement in this! I'll even mention your GitHub account (it's all I have :D) in our Twitter account (@GeoTux2) tomorrow when I announce the new version.

Regards, 
Germán

**Comment by BC14w** [comment]
Haha, No need to mention me, you did all the work! 
Thanks a lot! 
B-C

**Comment by gacarrillor** [comment]
You've un-starred 'Load Them All' GitHub's repo... :cry:

**Comment by BC14w** [comment]
haha! sorry about that. I'm still playing around all the tools on the website. I don't really know what everything is for yet. You have been restared!
