### ISSUE TITLE
QGIS 3.x Compatibility

### ISSUE THREAD

**Issue by Saijin-Naib** [gacarrillor/loadthemall#8]
Currently, loadthemall is not compatible with QGIS 3.x due to having been written for QGIS 2.x.

Would it be possible to forward-port it to QGIS 3.x,

Thanks!

**Comment by gacarrillor** [comment]
Hi!

right, this is planned! I'll try to migrate the plugin to QGIS 3 soon.

Regards, 

Germán

**Comment by gacarrillor** [comment]
Load Them All for QGIS v.3.x is near. 
Would you like to help testing it?

**Comment by Saijin-Naib** [comment]
Woo 😃
Absolutely!

How?

**Comment by gacarrillor** [comment]
You can download this [beta version](https://github.com/gacarrillor/loadthemall/files/2342981/loadthemall.zip) of the plugin and let me know of any issues you may find.

**Comment by gacarrillor** [comment]
Solved in https://github.com/gacarrillor/loadthemall/commit/f730a9d073dc3afd514a76477b2557155b906255!!!
Enjoy!
